name: kisan_sewa_kendra
description: "Krishi Bhandar shopify website's App"

publish_to: 'none'

version: 3.0.18+45

environment:
  sdk: ^3.5.3

dependencies: 
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.6.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.2
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5
  package_info_plus: ^10.2.1
  path_provider: ^2.1.5
  path: ^1.9.0

  cached_network_image: ^3.4.1
  cached_network_image_plus: ^0.0.5
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  flutter_widget_from_html: ^0.17.1
  fwfh_webview: ^0.15.6
  badges: ^3.2.0


  firebase_core: ^4.12.1
  firebase_analytics: ^12.4.5
  firebase_auth: ^6.5.6
  firebase_app_check: ^0.4.5+2
  firebase_remote_config: ^6.5.5
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.2.0
  facebook_app_events: ^0.30.3
  app_links: ^7.2.1
  geolocator: ^14.0.2
  geocoding: ^5.0.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^8.0.2
  carousel_slider: ^5.1.2
  font_awesome_flutter: ^11.0.0
  pinput: ^6.0.2
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7 

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/technical_names.json
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_native_splash.png

  android_12:
    color: "#FFFFFF"
    image: assets/logo_native_splash.png
  fullscreen: true
